### ISSUE TITLE
Protokoll für Umleitungen nicht hart codieren?

### ISSUE THREAD

**Issue by TN03** [olape-git/cmsimple-xh#1]
https://github.com/olape-git/cmsimple-xh/blob/cfa03f8f6f9574c9f1086c2eabc72385b86af560/cmsimple/seofuncs.php#L112

Wäre es nicht besser hier wirklich das bei der Anfrage verwendete Protokoll zu verwenden?
`$protocol=$_SERVER['PROTOCOL']`
Mein Server verwendet bereits HTTP/2.0

**Comment by olape-git** [comment]
Das wäre wohl auf jeden Fall besser
