### ISSUE TITLE
Umleitung zu verschlüsseltem Abruf nicht ohne Vorabprüfung

### ISSUE THREAD

**Issue by TN03** [olape-git/cmsimple-xh#2]
https://github.com/olape-git/cmsimple-xh/blob/cfa03f8f6f9574c9f1086c2eabc72385b86af560/cmsimple/seofuncs.php#L57
Wenn ein User die Umleitung aktiviert, der Server das aber nicht unterstützt, ist das Problem nur noch per FTP und Änderung der config.php zu lösen. 
Wenn wir das Feature wirklich einbauen, sollte vorher eine Prüfung durchgeführt werden.

Damit die Prüfung nicht bei jedem Request triggert, könnte man für die Auswahl über metaconfig.php vielleicht eine Funktion übergeben, die nur die mögliche(n) Option(en) anbietet.
Andere Ideen?

**Comment by TN03** [comment]
Vielleicht wäre es auch eine einfache Option, wenn die Checkbox im Falle eines Falles einfach per admin.js deaktiviert wird?

**Comment by olape-git** [comment]
Wenn der Server das nicht unterstützt ... ?
Das kann ich mir kaum vorstellen.
Aber, das es kein gültiges Zertifikat gibt, das könnte schon vorkommen.
Wie wöllte man das aber prüfen? Per cURL wäre vielleicht möglich.

Das Ganze ist, wenn auch bequem, per PHP eh nicht ganz ohne.
Auch https mit oder ohne www. erfordert in beiden Fällen ein Zertifikat, das beide Möglichkeiten abdeckt. Denn um eine Umleitung zu erreichen muss PHP erst mal unter dem jeweils nicht gewünschten ausgeführt werden.
IST DAS VERSTÄNDLICH?

**Comment by olape-git** [comment]
stream_socket_client() ist allerdings auch nicht überall verfügbar.
Wie das unter IIS aussieht habe ich noch nicht getestet.
Und aus der Checkbox würde ein DropDown werden.

**Code entfernt**

**Comment by manu37** [comment]
Ich bin jetzt mal etwas ketzerisch. Ist das wirklich die Aufgabe von CMSimple_XH? Der grosse Vorzug vom CMS ist doch, dass es problemlos kopiert/verschoben etc. werden kann. Mit dieser Einstellung wäre das nicht mehr gegeben. Die Weiterleitung lässt sich doch ganz einfach per .htaccess lösen.

**Comment by frase-git** [comment]
> Ich bin jetzt mal etwas ketzerisch. Ist das wirklich die Aufgabe von CMSimple_XH? Der grosse Vorzug vom CMS ist doch, dass es problemlos kopiert/verschoben etc. werden kann. Mit dieser Einstellung wäre das nicht mehr gegeben. Die Weiterleitung lässt sich doch ganz einfach per .htaccess lösen.

Sorry Olaf, aber das sehe ich ähnlich.
Auch wegen:

> Das Ganze ist, wenn auch bequem, per PHP eh nicht ganz ohne.
> Auch https mit oder ohne www. erfordert in beiden Fällen ein Zertifikat, das beide Möglichkeiten abdeckt. Denn um eine Umleitung zu erreichen muss PHP erst mal unter dem jeweils nicht gewünschten ausgeführt werden.

Vielleicht doch lieber nur per Plugin - oder besser per .htaccess.
Ich hätte mir sowas schon sehr gewünscht - es hat aber bei mir noch nie sauber funktioniert, wenn nicht zwei Zertifikate vorhanden sind (für mit und ohne www).
Übrigens auch nicht mit Hogers "adc-Plugin".

**Comment by olape-git** [comment]
Simple ist eben auf keinen Fall nicht htaccess.

Plugin ist leider auch nicht immer DAS Mittel der Wahl, da es momentan nicht möglich ist, zu beeinflussen, in welcher Reihenfolge die Plugins ins Spiel kommen. Allenfalls kann man versuchen, die Namen der alphabetischen Sortierung nach zu setzten und dann zu hoffen ...
Und an der Tatsache an sich würde sich auch als Plugin nichts ändern.

Deswegen finde ich diese Möglichkeit im CMS schon sehr gut.
Die Frage ist, ob man dem Anwender das Denken komplett abnehmen muss mit der Vorabprüfung, oder ob man nich wenigstens die Verantwortung für diese Einstellung in die Hände des Anwenders legen kann / sollte.
Denn auch bei jeder anderen Variante wäre der Anwender in der „Denkplicht“.
Und auch mit jeder anderen Variante kann man das CMS unbrauchbar machen,
so dass es nur per FTP wieder zu bereinigen geht.

Warum beide Varianten, mit und ohne www., vom Zertifikat abgedeckt werden müssen, habe ich auch schon versucht zu erklären.

Wenn wir das CMS voranbringen wollen, oder wenigstens sinnvoll am Leben erhalten wollen, dann, so denke ich, müssen wir schon eine Reihe von Features (bequem) mit einbringen.
Sonst kommt wieder der Vorwurf, alles nur für Freaks.

Und warum sollte man das Ganze deswegen nicht mehr kopieren können?

**Comment by manu37** [comment]
> Simple ist eben auf keinen Fall nicht htaccess.
```
RewriteEngine On
RewriteCond %{HTTPS} =off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [QSA,L,R=301]
```
Dieser Schalter bedingt Wartung, Dokumentation und kann mein System funktionsunfähig machen. Ist dies (CMS)simple? Für SSL muss ich mich ohnehin mit dem Thema befassen. Ist Dein Provider Dein Freund, geschieht dies mit Knopfdruck und er liefert die .htaccess gleich mit. Dieser Schalter verführt den DAU dazu zu meinen, mit Einschalten sei das SSL Problem gelöst.
Ohne Zweifel, Olaf, Deine Inputs sind grossartig. Aber gehört ein solches feature in einen bug fix release und sollten wir nicht wie früher solche Erweiterungen diskutieren. Oder habe ich was verpasst?
nix für ungut und Grüsse
manu

**Comment by olape-git** [comment]
> Dieser Schalter verführt den DAU dazu zu meinen, mit Einschalten sei das SSL Problem gelöst.

Genau darum geht es in dem Code. Es soll sich nur einstellen lassen, wenn es ein entsprechend passendes Zertifikat gibt.
Aber ich bin mir nicht sicher, ob man überhaupt so weit gehen muss.

Allerdings bin ich mir sehr sicher, dass die User heute Klick-lösungen bevorzugen.
Und leider bezieht sich das Simple bei XH nicht immer nur auf die Handhabung, sonder immer wieder mal auch auf die Ausstattung.

> und sollten wir nicht wie früher solche Erweiterungen diskutieren.

Ja, denn nur weil ich das gern so hätte, müssen wir das natürlich nicht tun.
So hatten wir uns per pm am 11.12.2019 verständigt.

Da es sich aber durch [https://github.com/cmsimple-xh/cmsimple-xh/issues/375](url) und [https://github.com/cmsimple-xh/cmsimple-xh/issues/282](url) geradezu aufgedrängt hat, das Thema gleich komplett abzuhaken, bin ich immer noch der Meinung, wir sollten das auf jeden Fall  tun. 
Vielleicht wäre es gut, die Konfiguration mit unter „erweitert“ zu verschieben.

**Comment by olape-git** [comment]
Übrigens, um noch mal auf das Kopieren zurückzukommen.
Wenn ich das System kopiere und SSL und www per htaccess geregelt ist, muss ich beim Kopieren auch aufpassen, ob das auf einem neuen Webspace / URL wieder passt.

Ich sehe also in dieser Hinsicht bei htaccess keinen Vorteil.

**Comment by manu37** [comment]
> Da es sich aber durch https://github.com/cmsimple-xh/cmsimple-xh/issues/375 und https://github.com/cmsimple-xh/cmsimple-xh/issues/282 geradezu aufgedrängt hat, das Thema gleich komplett abzuhaken, bin ich immer noch der Meinung, wir sollten das auf jeden Fall tun.

Bei diesen zwei issues gebe ich Dir vollkommen recht (die Linkziele stimmen nicht, der Linktext schon). Aber die rewrites sind ein anderes Thema.

**Comment by manu37** [comment]
> Wenn ich das System kopiere und SSL und www per htaccess geregelt ist, muss ich beim Kopieren auch aufpassen, ob das auf einem neuen Webspace / URL wieder passt.

Du meinst, weil ich die .htacces mit kopiere? Das stimmt. Diese kann ich aber löschen/renamen und nachher wieder zurücksetzen. Die configs bleiben erhalten.
Ich weiss, das Thema ist etwas fundamentalistisch. Aber eine zentrale Eigenschaft des CMS ist, dass ich es problemlos kopieren und laufen lassen kann. Die .htaccess gehört IMHO eher zur Serverumgebung und nicht zum System.

**Comment by TN03** [comment]
Ich bin eigentlich auch gegen die Aufnahme in den Core. Einwürfe bzgl. Zertifikat mit/ohne www stimmen zwar, beim Provider sollte das aber eh richtig konfiguriert sein (ich hatte da mit Let's encrypt bisher nie Probleme). Auch die Umleitung zu https geht i.d.R. im Dashboard des Hosters per Klick. 
@Olaf:  warum machen wir nicht einfach ein (verbessertes) Plugin daraus?
Zumal, wenn ich mich richtig erinnere, das Issue für 1.8 adressiert war.

**Comment by olape-git** [comment]
Die Mehrheit entscheidet.
Ich habe es trotzdem mal angepasst. Ihr könnt es euch ja mal ansehen.

Übrigens, auch wenn die Einstellung wirklich schief geht, kann man den Browser trotz allem überreden, die Seite aufzurufen. Man kann die Einstellung also auch ohne FTP zurücksetzen.

Ich fände es schade.

**Comment by olape-git** [comment]
Da fällt mir übrigens noch was anderes ein, nur so am Rande.
Immer wenn ich in der Vergangenheit irgendwo geschrieben habe, kann man per htaccess regeln, dann habe ich alsbald zu Antwort bekommen. Es soll aber für alle nutzbar sein, nicht nur für die, die die Möglichkeit htaccess haben.

**Comment by olape-git** [comment]
> warum machen wir nicht einfach ein (verbessertes) Plugin daraus?
Zumal, wenn ich mich richtig erinnere, das Issue für 1.8 adressiert war

[Integrate ADC plugin functionality #361](https://github.com/cmsimple-xh/cmsimple-xh/issues/361)
Stimmt, aber ich hatte ja schon geschrieben, es hat sich einfach angeboten.
Und warum sollte man dann absichtlich warten, wenn es denn fertig ist.

Wenn wir die Reihenfolge der Plugins festlegen könnten, dann wäre ich auch dafür.
Was auch für einige andere Plugins sehr nützlich wäre, wie etwa cnc.
So, wie es jetzt aber ist, ist es im Core besser aufgehoben.

**Comment by olape-git** [comment]
#https://github.com/cmsimple-xh/cmsimple-xh/commit/1471f8ba4a052d0a064a53c3c22ca05e7d519ffe
